version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_codeszn
        ports:
            - '27019:27017'
        volumes:
            - codeszn:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    codeszn:
